networks:
  vault-net:
    driver: bridge

  jenkins-net:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    restart: unless-stopped
    networks:
      vault-net: {}
      jenkins-net: {}
    tty: true
    env_file: .env
    ports:
      - "8088:8080"
      - "50000:50000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${LOCAL_VOLUME_PATH}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VAULT_ADDR: "https://vault:8200"


  agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID:-999}
    privileged: true
    user: root
    container_name: agent
    networks:
      jenkins-net: {}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - grype-db:/var/cache/grype
    expose:
      - 22
    environment:
      - GRYPE_DB_AUTO_UPDATE=true
      - GRYPE_DB_CACHE_DIR=/var/cache/gryp
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_PUBLIC_KEY}

volumes:
  grype-db: